- name: Make sure ca-certificates package is the latest
  yum:
    name: ca-certificates
    state: latest

# This is just for locking, if you don't need locking just remove/ignore them
# Locking is done using filesystem, good if you have cluster with a shared filesystem (like NFS), so only one node will do the wallet building and place it it a shared filesystem
- block:
  - name: Try getting a lock to write mozilla wallet file
    shell: "touch {{ cawalletlocktmp }} && ln {{ cawalletlocktmp }} {{ cawalletlock }}"
    register: getlock
    failed_when: no
  - set_fact:
      cawalletlockgranted: yes
    when: getlock.rc == 0
  always:
    - name: Remove temporary lock
      file:
        name: "{{ cawalletlocktmp }}"
        state: absent
    - name: Remove global lock
      file:
        name: "{{ cawalletlock }}"
        state: absent
      when: getlock.rc == 0


# The actial wallet building
- block:

  - name: Create temporary directories
    file:
      path: "{{ item }}"
      state: directory
    with_items:
      - "{{ tmp_wallet }}"
      - "{{ tmp_cert_extract }}"

  - name: Extract certificates
    shell: rm -f * && csplit {{ source_ca_certs }} '/-----BEGIN CERTIFICATE-----/' '{*}' && rm xx00
    args:
      chdir: "{{ tmp_cert_extract }}"

  - name: Create new wallet
    shell: "{{ oracle_home }}/bin/orapki wallet create -wallet {{ tmp_wallet }} -pwd {{ wallet_password }}"
    environment:
      ORACLE_HOME: "{{ oracle_home }}"

  - name: Import all trusted certificates
    shell: find . -name 'xx*' -type f -exec {{ oracle_home }}/bin/orapki wallet add -wallet {{ tmp_wallet }} -trusted_cert -cert {} -pwd {{ wallet_password }} \;
    args:
      chdir: "{{ tmp_cert_extract }}"    
    environment:
      ORACLE_HOME: "{{ oracle_home }}"

  - name: Replace wallet
    shell: mkdir -p {{ target_wallet }} && rm -f {{ target_wallet }}/ewallet* && mv {{ tmp_wallet }}/ewallet.p12 {{ target_wallet }}/

  when: cawalletlockgranted

- name: Clean temporary directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmp_wallet }}"
    - "{{ tmp_cert_extract }}"
